mic-feednews-api-web:
  build: web/
  tty: true
  ports:
    - "8136:80"
  volumes:
    - ../:/var/www/html
  links:
    - mic-feednews-api-mysql:mysql
  environment:
    ENVIRONMENT: docker
  container_name: mic-feednews-api-web

mic-feednews-api-mysql:
  build: mysql/
  ports:
    - "33114:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=123456
  container_name: mic-feednews-api-mysql

mic-feednews-api-pma:
  image: pitchanon/phpmyadmin:latest
  ports:
    - "32066:80"
  volumes:
    - .:/var/www/html
  links:
    - mic-feednews-api-mysql:mysql
  container_name: mic-feednews-api-pma
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mic-feednews-api-mysql
    - PMA_PORT=3306
    - PMA_USER=root
    - PMA_PASSWORD=123456
